name: 'lev-p-ai-review'
description: 'Automatic code review for React + TypeScript projects'
author: 'lev-p'
branding:
  icon: 'code'
  color: 'blue' 

inputs:
  deepseek-api-key:
    description: 'DeepSeek API key'
    required: true
  github-token:
    description: 'GitHub token (provided automatically)'
    required: true
    default: ${{ github.token }}

runs:
  using: 'node20'
  main: 'dist/index.js' 