name: 'lev-p-ai-review'
description: 'Automatic code review for React + TypeScript projects'
author: 'lev-p'
branding:
  icon: 'code'
  color: 'blue' 

inputs:
  DEEPSEEK_API_KEY:
    description: 'DeepSeek API key'
    required: true
  GITHUB_TOKEN:
    description: 'GitHub token (provided automatically)'
    required: true
    default: ${{ github.token }}
  PR_NUMBER:
    description: 'Pull request number'
    required: true
    default: ${{ github.event.pull_request.number }}
  GITHUB_REPOSITORY:
    description: 'Repository name with owner'
    required: true
    default: ${{ github.repository }}
  GITHUB_EVENT_NAME:
    description: 'Name of the event that triggered the workflow'
    required: true
    default: ${{ github.event_name }}

runs:
  using: 'node20'
  main: 'dist/index.js'