name: Code Review

on:
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [created]
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  review:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' || github.event.issue.pull_request || github.event.comment.body && (startsWith(github.event.comment.body, '@ai') || startsWith(github.event.comment.body, '/ai'))
    steps:
      - uses: actions/checkout@v4
      
      - name: AI Code Review
        uses: malaev/ai-review@v0.1.29
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEEPSEEK_API_KEY: ${{ secrets.DEEPSEEK_API_KEY }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          PR_NUMBER: ${{ github.event.pull_request.number || github.event.issue.number }}
          COMMENT_ID: ${{ github.event.comment.id }} 